(eval-when-compile
  (require 'color-theme))

(defun color-theme-underwater ()
  "A port of Dmityry Kichenko's underwater theme"
  (interactive)
  (color-theme-install
   '(color-theme-underwater
     ((foreground-color . "white")
      (background-color . "#18374f")
      (cursor-color . "#ffa096")
      (background-mode . dark))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :italic t))))
     (default ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "white"))))
     (font-lock-comment-face ((t (:foreground "#3e71a1" :bold t))))
     (font-lock-constant-face ((t (:foreground "#96defa"))))
     (font-lock-function-name-face ((t (:foreground "#af81f4"))))
     (font-lock-keyword-face ((t (:foreground "#8ac6f2"))))
     (font-lock-preprocessor-face ((t (:foreground "#ef6145"))))
;;     (font-lock-reference-face ((t (:foreground "SteelBlue"))))
     (font-lock-string-face ((t (:foreground "#89e14b"))))
     (font-lock-type-face ((t (:foreground "white"))))
     (font-lock-variable-name-face ((t (:foreground "white"))))
     (font-lock-warning-face ((t (:foreground "Orchid" :bold t))))
     ;; (highlight ((t (:background "darkseagreen2"))))
     ;; (italic ((t (:italic t))))
     ;; (modeline ((t (:foreground "gray80" :background "black"))))
     ;; (modeline-buffer-id ((t (:foreground "gray80" :background "black"))))
     ;; (modeline-mousable ((t (:foreground "gray80" :background "black"))))
     ;; (modeline-mousable-minor-mode ((t (:foreground "gray80" :background "black"))))
     ;; (region ((t (:background "gray"))))
     ;; (secondary-selection ((t (:background "paleturquoise"))))
     ;; (show-paren-match-face ((t (:foreground "yellow" :background "darkgreen"))))
     ;; (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
     ;; (underline ((t (:underline t))))
)))
