(require 'color-theme)
(color-theme-initialize)
(load-library "color-theme-molokai")
(color-theme-molokai)
;;(load-library "sublime-text-2.el")
;;(sublime-text-2)
;; (load-library "color-theme-underwater.el")
;; (load-library "color-theme-sunburst.el")
;; (color-theme-tm)

(provide 'themes)
